In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
creditcartdata = pd.read_csv('creditcard.csv')

In [3]:
creditcartdata.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
creditcartdata.tail(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
39697,39927,-1.466679,2.425732,0.877724,3.950765,0.762477,1.162748,0.575625,-0.288354,-1.357990,...,0.186051,0.571010,-0.107517,-0.754306,-0.752828,0.113179,-2.079421,-0.809173,1.50,0.0
39698,39927,-0.523165,-0.100021,0.892966,-1.900405,-0.156870,-0.783894,0.917683,-0.308345,-1.305284,...,-0.082504,-0.414677,-0.063392,-0.087455,-0.303383,-0.682889,-0.178417,-0.137169,100.92,0.0
39699,39928,-2.768425,-1.007072,2.151127,0.117797,1.283178,1.869731,-0.562240,0.820374,0.348797,...,-0.182963,0.778210,0.904077,-1.288631,0.212441,0.483975,-0.027614,-0.582813,11.99,0.0
39700,39928,1.201327,0.158614,-0.325263,0.471667,0.086446,-0.770357,0.422151,-0.205277,-0.451865,...,0.027664,-0.018485,-0.199382,0.053605,0.683829,0.428416,-0.077342,-0.006394,45.00,0.0
39701,39929,1.097669,-1.315782,0.659681,-0.683915,-1.342612,0.332629,-1.110900,0.194811,-0.248825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
creditcartdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39702 entries, 0 to 39701
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    39702 non-null  int64
 1   V1      39702 non-null  float64
 2   V2      39702 non-null  float64
 3   V3      39702 non-null  float64
 4   V4      39702 non-null  float64
 5   V5      39702 non-null  float64
 6   V6      39702 non-null  float64
 7   V7      39702 non-null  float64
 8   V8      39702 non-null  float64
 9   V9      39702 non-null  float64
 10  V10     39702 non-null  float64
 11  V11     39702 non-null  float64
 12  V12     39702 non-null  float64
 13  V13     39701 non-null  float64
 14  V14     39701 non-null  float64
 15  V15     39701 non-null  float64
 16  V16     39701 non-null  float64
 17  V17     39701 non-null  float64
 18  V18     39701 non-null  float64
 19  V19     39701 non-null  float64
 20  V20     39701 non-null  float64
 21  V21     39701 non-null  float64
 22  V22     39701 non-null  float64
 23  V23     39701 non-null  float64
 24  V24     39701 non-null  float64
 25  V25     39701 non-null  float64
 26  V26     39701 non-null  float64
 27  V27     39701 non-null  float64
 28  V28     39701 non-null  float64
 29  Amount  39701 non-null  float64
 30  Class   39701 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 9.4 MB

In [6]:
#checking the number of missing values in each column

creditcartdata.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
#droping missing values

creditcartdata.dropna(inplace=True)

In [8]:
creditcartdata.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
#checking the distribution of legit transaction and fraudulent transaction

creditcartdata['Class'].value_counts()

Class
0.0    39597
1.0      104
Name: count, dtype: int64

seperating the data for analysis

0 ---> Normal transaction
1 ---> fraud transaction

In [25]:
legit_cases = creditcartdata[creditcartdata.Class == 0]
fraud_cases = creditcartdata[creditcartdata.Class  == 1]

In [26]:
fraud_cases

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,frauds
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0,True
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0,True
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0,True
6108,6986,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1.0,True
6329,7519,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0,True
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0,True
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0,True
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0,True
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0,True

In [32]:
legit_cases.shape

(39597, 32)

In [31]:
fraud_cases.shape

(104, 32)

In [33]:
legit_cases['Amount'].describe()

count    39597.000000
mean        87.420700
std        234.514383
min          0.000000
25%          7.420000
50%         23.500000
75%         79.000000
max       7879.420000
Name: Amount, dtype: float64

In [34]:
fraud_cases['Amount'].describe()

count     104.000000
mean       97.070769
std       255.012160
min         0.000000
25%         1.000000
50%         3.775000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [35]:
#compare the values

creditcartdata.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,frauds
Class,,,,,,,,,,,,,,,,,,,,,
0.0,25514.725686,-0.194310,0.036967,0.744162,0.174545,-0.217414,0.107151,-0.093182,0.031783,0.222434,...,-0.031386,-0.111706,-0.039470,0.007851,0.135895,0.022779,0.005987,0.003920,87.420700,0.0
1.0,20683.201923,-7.697309,5.766703,-10.853666,5.865850,-5.424996,-2.275717,-7.641867,3.827809,-2.924282,...,0.626795,-0.345972,-0.342944,-0.230514,0.299242,0.176522,0.811431,0.099914,97.070769,1.0

Under-Sampling

Build a sample dataset containing similar distribution of normal transaction and fradulent transaction

Number of fradulent transaction -----> 104

In [36]:
legist_sample = legit_cases.sample(n=104)

Concantenate 2 DF

In [37]:
new_dataset = pd.concat([legist_sample, fraud_cases], axis=0)

In [38]:
new_dataset.shape

(208, 32)

In [39]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,frauds
8137,11032,1.302043,-0.261503,-0.722756,-0.853728,1.700463,3.426329,-1.013726,0.793970,1.596136,...,-0.231570,-0.051550,1.022013,0.368303,1.046159,-0.086748,-0.000809,15.95,0.0,False
4135,3746,1.396557,-0.469881,0.670583,-0.441149,-1.212393,-1.039399,-0.755433,-0.173049,0.785281,...,-0.736143,0.163942,0.260853,0.142722,-0.514767,-0.029728,0.013491,15.00,0.0,False
1534,1204,1.364563,-1.178268,0.650371,-1.283988,-1.740504,-0.877664,-0.948682,-0.222741,-1.824012,...,-0.707460,0.110777,0.357286,0.122213,-0.419706,0.032784,0.043429,84.68,0.0,False
38405,39383,-1.632221,-1.480038,0.761254,-1.844751,-1.997940,-0.165357,0.583220,0.284342,-0.397963,...,-0.437262,0.638687,-0.164764,0.483235,0.119165,-0.130539,-0.044209,400.55,0.0,False
13139,23071,-0.631679,1.016919,1.339009,0.251583,0.278218,-0.543860,0.440446,0.003316,1.109489,...,-0.826273,0.184266,-0.067839,-0.265271,0.059364,0.114322,0.067933,4.49,0.0,False

In [40]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,frauds
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0,True
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0,True
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0,True
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0,True
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0,True

In [41]:
new_dataset['Class'].value_counts()

Class
0.0    104
1.0    104
Name: count, dtype: int64

In [42]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,frauds
Class,,,,,,,,,,,,,,,,,,,,,
0.0,24714.134615,-0.068690,0.154906,0.910373,-0.163275,-0.305602,0.060688,-0.180719,-0.173622,0.385324,...,0.125464,-0.174137,0.005009,0.090784,0.106031,0.128050,0.011693,0.000837,55.033269,0.0
1.0,20683.201923,-7.697309,5.766703,-10.853666,5.865850,-5.424996,-2.275717,-7.641867,3.827809,-2.924282,...,0.626795,-0.345972,-0.342944,-0.230514,0.299242,0.176522,0.811431,0.099914,97.070769,1.0

Splitting the data into feature and target

In [44]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [45]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
8137   11032  1.302043 -0.261503 -0.722756 -0.853728  1.700463  3.426329
4135    3746  1.396557 -0.469881  0.670583 -0.441149 -1.212393 -1.039399
1534    1204  1.364563 -1.178268  0.650371 -1.283988 -1.740504 -0.877664
38405  39383 -1.632221 -1.480038  0.761254 -1.844751 -1.997940 -0.165357
13139  23071 -0.631679  1.016919  1.339009  0.251583  0.278218 -0.543860
...      ...       ...       ...       ...       ...       ...       ...
30473  35942 -4.194074  4.382897 -5.118363  4.455230 -4.812621 -1.224645
30496  35953 -4.844372  5.649439 -6.730396  5.252842 -4.409566 -1.740767
31002  36170 -5.685013  5.776516 -7.064977  5.902715 -4.715564 -1.755633
33276  37167 -7.923891 -5.198360 -3.000024  4.420666  2.272194 -3.394483
39183  39729 -0.964567 -1.643541 -0.187727  1.158253 -2.458336  0.852222

             V7        V8        V9  ...       V21       V22       V23  \
8137  -1.013726  0.793970  1.596136  ... -0.119160 -0.231570 -0.051550
4135  -0.755433 -0.173049  0.785281  ... -0.263201 -0.736143  0.163942
1534  -0.948682 -0.222741 -1.824012  ... -0.319807 -0.707460  0.110777
38405  0.583220  0.284342 -0.397963  ... -0.040937 -0.437262  0.638687
13139  0.440446  0.003316  1.109489  ... -0.391497 -0.826273  0.184266
...         ...       ...       ...  ...       ...       ...       ...
30473 -7.281328  3.332250 -3.679659  ...  1.550473  0.614573  0.028521
30496 -6.311699  3.449167 -5.416284  ...  1.194888 -0.845753  0.190674
31002 -6.958679  3.877795 -5.541529  ...  1.128641 -0.962960 -0.110045
33276 -5.283435  0.131619  0.658176  ... -0.734308 -0.599926 -4.908301
39183  2.785163 -0.303609  0.940006  ...  0.447180  0.536204  1.634061

            V24       V25       V26       V27       V28  Amount  frauds
8137   1.022013  0.368303  1.046159 -0.086748 -0.000809   15.95   False
4135   0.260853  0.142722 -0.514767 -0.029728  0.013491   15.00   False
1534   0.357286  0.122213 -0.419706  0.032784  0.043429   84.68   False
38405 -0.164764  0.483235  0.119165 -0.130539 -0.044209  400.55   False
13139 -0.067839 -0.265271  0.059364  0.114322  0.067933    4.49   False
...         ...       ...       ...       ...       ...     ...     ...
30473  0.013704 -0.149512 -0.131687  0.473934  0.473757   14.46    True
30496 -0.216443 -0.325033 -0.270328  0.210214  0.391855  111.70    True
31002 -0.177733 -0.089175 -0.049447  0.303445  0.219380  111.70    True
33276  0.410170 -1.167660  0.520508  1.937421 -1.552593   12.31    True
39183  0.203839  0.218749 -0.221886 -0.308555 -0.164500  776.83    True

[208 rows x 31 columns]

In [46]:
Y

8137     0.0
4135     0.0
1534     0.0
38405    0.0
13139    0.0
        ...
30473    1.0
30496    1.0
31002    1.0
33276    1.0
39183    1.0
Name: Class, Length: 208, dtype: float64

Split the data into training and test data

In [47]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [48]:
print(X.shape,X_train.shape,X_test.shape)

(208, 31) (166, 31) (42, 31)

Training the model

Logistic regression

In [49]:
model = LogisticRegression()

In [50]:
#training the logistic regression model

model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evualuation

In [51]:
#Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [52]:
training_data_accuracy

0.9819277108433735

In [54]:
#Accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [55]:
test_data_accuracy

0.9761904761904762